### ISSUE TITLE
Checkbox group & Radio group - touched before any input

### ISSUE THREAD

**Issue by faberv** [tvaliasek/vue-form-inputs#11]
Both groups are `touch`ed immediately, without waiting for user input. It causes that validation messages to appear immediately after page is loaded:

![image](https://user-images.githubusercontent.com/2473221/232069361-a6246afc-bb9d-4a20-b97d-405d40d4b9ff.png)

**Comment by tvaliasek** [comment]
Resolved by updating bs vue next
