### ISSUE TITLE
FormInputDatePicker - validation state icon overlaps native input clear button

### ISSUE THREAD

**Issue by faberv** [tvaliasek/vue-form-inputs#9]
![image](https://user-images.githubusercontent.com/2473221/227909000-e29d731d-95e0-450a-85ce-22b41211a56f.png)

## How to reproduce
1. Use component `FormInputDatePicker`
2. Set some validations for this input
3. Pick date using date picker

**Comment by tvaliasek** [comment]
Resolved in latest release
